spring:
  profiles:
    active: local
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto:  validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
payment_transaction:
  complete_time: 1h
  cron: 0 */2 * ? * *
