spring:
  profiles:
    active: local
  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto:  validate
  flyway:
    enabled: true
    baseline-on-migrate: true
    out-of-order: true
server:
  port: 8081
payment-transaction:
  complete-time: 1H
  cron: 0 */2 * ? * *
