#Defines application configs:
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1010464817547-k3se62nnmccutia6dfocdi0kfl7hdsce.apps.googleusercontent.com
            client-secret: iAQ5Im8Fin9QJlUTKNgMTu7T
            accessTokenUri: https://www.googleapis.com/oauth2/v4/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
            clientAuthenticationScheme: form
            userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
            preferTokenInfo: true
            scope: openid,email,profile
  activemq:
    broker-url: tcp://${ACTIVEMQ_HOST}:61616
    user: admin
    password: admin
  redis:
    host: ${REDIS_HOST}
    port: 6379

